///////////////////////////////////////////////////////////
//  cArticulos.cs
//  Implementation of the Class cArticulos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:20
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cArticulos {

	private struct Dimensiones;
	private readonly float peso;
	private readonly float volumen;

	public cArticulos(){

	}

	~cArticulos(){

	}

}//end cArticulos