///////////////////////////////////////////////////////////
//  cCamioneta.cs
//  Implementation of the Class cCamioneta
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:28
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cCamioneta : cVehiculos {

	public cCamioneta(){

	}

	~cCamioneta(){

	}

}//end cCamioneta