///////////////////////////////////////////////////////////
//  cCamion.cs
//  Implementation of the Class cCamion
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:24
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cCamion : cVehiculos {

	public cCamion(){

	}

	~cCamion(){

	}

}//end cCamion