///////////////////////////////////////////////////////////
//  cCliente.cs
//  Implementation of the Class cCliente
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:33
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cCliente {

	private readonly string DNI;
	public cUbicacion m_cUbicacion;

	public cCliente(){

	}

	~cCliente(){

	}

}//end cCliente