///////////////////////////////////////////////////////////
//  cCocimundo.cs
//  Implementation of the Class cCocimundo
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:14
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Xml.Schema;
using System.Security.Cryptography.X509Certificates;

public class cCocimundo {

	public List<cVehiculos> ListaVehiculos;
	public List<cPedidos> ListaPedidos;
    private double Dinero;

	public cCocimundo(){
		ListaPedidos = new List<cPedidos>();
		ListaVehiculos = new List<cVehiculos>();
        Dinero = 1000000;

    }
    public double getDinero() { return Dinero; }
    public void MasDinero(double entrante) { Dinero += entrante; }
    public void MenosDinero(double saliente) { Dinero -= saliente; }

    ~cCocimundo(){


    
	}
    public void ImprimirMatriz(int[,] matriz, int fila, int columna)
    {
        Console.WriteLine("Matriz");
        for(int i = 0; i < fila; i++)
        {
        
            for (int j = 0; j < columna; j++)
            {
                Console.WriteLine(matriz[i,j]);
               
            }
           
        }
       
    }
	public void AgregarPedido(cPedidos pedido){
		ListaPedidos.Add(pedido);
			}

	public void EliminarPedido(cPedidos pedido)
	{
		ListaPedidos.Remove(pedido);
	}

	public void FinalDelDia(){
		for (int i = 0; i < ListaPedidos.Count; i++)
		{
			ListaPedidos[i].ModificarPrioridad();
        }
        Console.WriteLine("\n\n\nEl dinero final fue de: {0} pesos, la ganancia neta total fue de: {1} pesos", Convert.ToString(Dinero), Convert.ToString(Dinero - 1000000));

    }

    public void OrdenarListaPedidos()
    {
        ListaPedidos = ListaPedidos.OrderBy(cPedidos => cPedidos.Cliente.m_cUbicacion.GetBarrio()).ToList();
        ListaPedidos = ListaPedidos.OrderBy(cPedidos => cPedidos.getPrioridad()).ToList();
    }

    public double funcionDistancia(cPedidos desde, cPedidos hasta)
	{
		double distancia = 0;
		if (desde.Cliente.m_cUbicacion.GetBarrio() == hasta.Cliente.m_cUbicacion.GetBarrio())
			distancia = Math.Sqrt(Math.Pow(hasta.Cliente.m_cUbicacion.getX(), 2) + Math.Pow(hasta.Cliente.m_cUbicacion.getY(), 2));
		else
			distancia = Math.Sqrt(Math.Pow(hasta.Cliente.m_cUbicacion.getX() - desde.Cliente.m_cUbicacion.getX(), 2) 
				+ Math.Pow(hasta.Cliente.m_cUbicacion.getY() - desde.Cliente.m_cUbicacion.getY(), 2));
		return distancia;
	}
    
    public List<cPedidos> Dinamico_Mochila(cVehiculos vehiculo)
    {
	
		int numpedidos = ListaPedidos.Count();
        int volumen = vehiculo.getVol_Max();

        int[,] Matriz = new int[numpedidos +1 , vehiculo.getVol_Max() +1]; //Crea una matriz de dimensiones N: numero de pedidos total y M: volumen maximo del vehiculo pasado por parametro
		List<cPedidos> sublistapedidos = new List<cPedidos>();
        int value;
        for (int i = 0; i < numpedidos; i++)
        {
            for (int w = 0; w < volumen; w++)
            {
                if (w == 0 || i == 0) //Llena la primer columna y la primer fila de la matriz con 0
                {
                    Matriz[i, w] = 0;
                }
                else if (ListaPedidos[i - 1].getVolumen() <= w)
                {
                    value = ListaPedidos[i - 1].getValue() + Matriz[i - 1, w - (int)(ListaPedidos[i - 1].getVolumen())];

                    if (value > Matriz[i - 1, w])
                    // Se compara el value entre el valor del producto +  la matriz del (volumen - el peso del objeto anterior)  y la posicion anterior de la matriz

                    {
                        sublistapedidos.Add(ListaPedidos[i]);
                        Matriz[i, w] = value;
                    }
                    else
                    {
                        Matriz[i, w] = Matriz[i - 1, w];
                    }
                }
                else //No entraba en la mochila, se queda con el valor anterior
                {
                    Matriz[i, w] = Matriz[i - 1, w];
                }
        
            }

            
        }
        ImprimirMatriz(Matriz, numpedidos + 1, volumen + 1);
        return sublistapedidos; //devuelve la sublista de pedidos
    }

	public List<cPedidos> Distribucion_greedy(List<cPedidos>ListaAOrdenar, cVehiculos Vehiculo)
	{
		List<cPedidos> ListaOrdenada = new List<cPedidos>();
		int pos = 0, cant = ListaAOrdenar.Count;
		double distancia = 0, distancia_total = 0;
		for(int j = 0; j< cant; j++)
		{
			if(j == 0)
			{
				distancia = funcionDistancia(ListaAOrdenar[j], ListaAOrdenar[j]);
				pos = j;
				for(int i = 0; i< ListaAOrdenar.Count;i++)
				{
					if (distancia > funcionDistancia(ListaAOrdenar[i], ListaAOrdenar[i]))
					{
                        distancia = funcionDistancia(ListaAOrdenar[i], ListaAOrdenar[i]);
						pos = i;
                    }
                }
				ListaOrdenada.Add(ListaAOrdenar[pos]);
                ListaAOrdenar.Remove(ListaAOrdenar[pos]);
                distancia_total += distancia;

            }
            else
			{
                distancia = 99999999999;
                pos = j;
                for (int i = 0; i < ListaAOrdenar.Count; i++)
                {
                    if (distancia > funcionDistancia(ListaOrdenada.Last(), ListaAOrdenar[i]))
                    {
                        distancia = funcionDistancia(ListaOrdenada.Last(), ListaAOrdenar[i]);
                        pos = i;
                    }
                }
                ListaOrdenada.Add(ListaAOrdenar[pos]);
                ListaAOrdenar.Remove(ListaAOrdenar[pos]);
                distancia_total += distancia;
            }
        }
        Vehiculo.setdistanciarecorrida(distancia_total + funcionDistancia(ListaOrdenada.Last(), ListaOrdenada.Last()));
		return ListaOrdenada;
	}

    public double NaftadelVjaje(cVehiculos Vehiculo)
    {
        return Vehiculo.getdistanciarecorrida() * Vehiculo.getconsumo();

    }
    public void CargarPedidos()
    {
#region Ubicaciones
        cUbicacion Comuna1 = new cUbicacion(eBarrio.Comuna_1);
        cUbicacion Comuna2 = new cUbicacion(eBarrio.Comuna_2);
        cUbicacion Comuna3 = new cUbicacion(eBarrio.Comuna_3);
        cUbicacion Comuna4 = new cUbicacion(eBarrio.Comuna_4);
        cUbicacion Comuna5 = new cUbicacion(eBarrio.Comuna_5);
        cUbicacion Comuna6 = new cUbicacion(eBarrio.Comuna_6);
        cUbicacion Comuna7 = new cUbicacion(eBarrio.Comuna_7);
        cUbicacion Comuna8 = new cUbicacion(eBarrio.Comuna_8);
        cUbicacion Comuna9 = new cUbicacion(eBarrio.Comuna_9);
        cUbicacion Comuna10 = new cUbicacion(eBarrio.Comuna_10);
        cUbicacion Comuna11 = new cUbicacion(eBarrio.Comuna_11);
        cUbicacion Comuna12 = new cUbicacion(eBarrio.Comuna_12);
        cUbicacion Comuna13 = new cUbicacion(eBarrio.Comuna_13);
        cUbicacion Comuna14 = new cUbicacion(eBarrio.Comuna_14);
        cUbicacion Comuna15 = new cUbicacion(eBarrio.Comuna_15);
        cUbicacion VicenteLopez = new cUbicacion(eBarrio.VicenteLopez);
        cUbicacion SanIsidro = new cUbicacion(eBarrio.SanIsidro);
        cUbicacion SanMartin = new cUbicacion(eBarrio.SanMartin);
        cUbicacion TresdeFebrero = new cUbicacion(eBarrio.TresdeFebrero);
        cUbicacion Moron = new cUbicacion(eBarrio.Moron);
        cUbicacion LaMatanza = new cUbicacion(eBarrio.LaMatanza);
        cUbicacion LomasdeZamora = new cUbicacion(eBarrio.LomasdeZAmora);
        cUbicacion Lanus = new cUbicacion(eBarrio.Lanus);
        cUbicacion Avellaneda = new cUbicacion(eBarrio.Avellaneda);
#endregion

#region clientes
        cCliente Cliente1 = new cCliente("Juan Perez", "11111111", Comuna1);
        cCliente Cliente2 = new cCliente("Santiago Gambach", "22222222", Comuna2);
        cCliente Cliente3 = new cCliente("Tomas Conde", "33333333", Comuna3);
        cCliente Cliente4 = new cCliente("Silvia Paterno", "44444444", Comuna4);
        cCliente Cliente5 = new cCliente("Joaquin Conde", "55555555", Comuna5);
        cCliente Cliente6 = new cCliente("Estaban Quito", "6666666", Comuna6);
        cCliente Cliente7 = new cCliente("Broco Lee", "77777777", Comuna7);
        cCliente Cliente8 = new cCliente("Aquiles Bailoyo", "88888888", Comuna8);
        cCliente Cliente9 = new cCliente("Aquiles Vaesa", "99999999", Comuna9);
        cCliente Cliente10 = new cCliente("Taylor Swift", "12121212", Comuna10);
        cCliente Cliente11 = new cCliente("Matias Ducombs", "23232323", Comuna11);
        cCliente Cliente12 = new cCliente("Juanes", "34343434", Comuna12);
        cCliente Cliente13 = new cCliente("Wos", "45454545", Comuna13);
        cCliente Cliente14 = new cCliente("Nicolas Villavicencio", "56565656", Comuna14);
        cCliente Cliente15 = new cCliente("Nicolas Del Canio", "67676767", Comuna15);
        cCliente Cliente16 = new cCliente("Sergio Massa", "78787878", VicenteLopez);
        cCliente Cliente17 = new cCliente("Messi Messi", "89898989", SanIsidro);
        cCliente Cliente18 = new cCliente("Sergio Aguero", "90909090", SanMartin);
        cCliente Cliente19 = new cCliente("Juana Perez", "01010101", TresdeFebrero);
        cCliente Cliente20 = new cCliente("Juan Francisco Perez", "00001111", Moron);
        cCliente Cliente21 = new cCliente("Juan Manuel Perez", "11112222", LaMatanza);
        cCliente Cliente22 = new cCliente("Santiago Gonzalez", "98765432", LomasdeZamora);
        cCliente Cliente23 = new cCliente("Nicolas Berli", "1234578", Lanus);
        cCliente Cliente24 = new cCliente("Alejo Alvarez", "98761234", Avellaneda);
        #endregion
        //faltaria el precio de cada uno
#region Pedidos
        cPedidos Pedido1 = new cPedidos(Cliente1, ePrioridad.EXPRESS, "Monitor", 71.48, 99.74, 58.58, 3.39,eTipoArt.Electronico, 18349.89);
        cPedidos Pedido2 = new cPedidos(Cliente2, ePrioridad.NORMAL, "Impresora", 14.46, 99.03, 47.06, 1.4, eTipoArt.Electronico, 57644.43);
        cPedidos Pedido3 = new cPedidos(Cliente3, ePrioridad.DIFERIDO, "Televisor 55", 47.74, 84.9, 51.6, 14.6, eTipoArt.Televisor, 95857.33);
        cPedidos Pedido4 = new cPedidos(Cliente4, ePrioridad.EXPRESS, "Termotanque", 65.93, 69.73, 11.51, 38,eTipoArt.Linea_Blanca, 37344.75);
        cPedidos Pedido5 = new cPedidos(Cliente5, ePrioridad.NORMAL, "Monitor", 71.48, 99.74, 58.58, 3.39, eTipoArt.Electronico, 18349.89);
        cPedidos Pedido6 = new cPedidos(Cliente6, ePrioridad.DIFERIDO, "Secarropas", 84.1, 97.65, 57.06, 10.9, eTipoArt.Linea_Blanca, 32279.94);
        cPedidos Pedido7 = new cPedidos(Cliente7, ePrioridad.EXPRESS, "Heladera", 39.94, 92.79, 37.24, 45, eTipoArt.Linea_Blanca, 31568.23);
        cPedidos Pedido8 = new cPedidos(Cliente8, ePrioridad.NORMAL, "Molinillo de Cafe", 99.03, 92.3, 88.22, 4.46, eTipoArt.PequeElectro, 27265.86);
        cPedidos Pedido9 = new cPedidos(Cliente9, ePrioridad.DIFERIDO, "Mouse", 10.73, 90.1, 93.02, 0.100, eTipoArt.Electronico, 23332.94);
        cPedidos Pedido10 = new cPedidos(Cliente10, ePrioridad.EXPRESS, "Webcam", 39.19, 10.9, 88.89, 0.150, eTipoArt.Electronico, 15017.83);
        cPedidos Pedido11 = new cPedidos(Cliente11, ePrioridad.NORMAL, "Televisor 52", 33.73, 50.59, 134.41, 11.5, eTipoArt.Televisor, 56517.98);
        cPedidos Pedido12 = new cPedidos(Cliente12, ePrioridad.DIFERIDO, "Televisor 75", 73.85, 57.0, 10.44, 33.3, eTipoArt.Televisor, 46780.86);
        cPedidos Pedido13 = new cPedidos(Cliente13, ePrioridad.EXPRESS, "Televisor 90", 84.93, 32.79, 187.71, 64, eTipoArt.Televisor, 68531.86);
        cPedidos Pedido14 = new cPedidos(Cliente14, ePrioridad.NORMAL, "Cafetera", 70.94, 41.15, 75.37, 2.3, eTipoArt.PequeElectro, 47197.11);
        cPedidos Pedido15 = new cPedidos(Cliente15, ePrioridad.DIFERIDO, "Heladera", 39.94, 92.79, 37.24, 45, eTipoArt.Linea_Blanca, 31568.23);
        cPedidos Pedido16 = new cPedidos(Cliente16, ePrioridad.EXPRESS, "Computadora Personal", 61.37, 38.28, 28.43, 2.5, eTipoArt.Electronico, 20908.25);
        cPedidos Pedido17 = new cPedidos(Cliente17, ePrioridad.NORMAL, "Teclado", 92.31, 79.94, 52.1, 0.55, eTipoArt.Electronico, 34657.74);
        cPedidos Pedido18 = new cPedidos(Cliente18, ePrioridad.DIFERIDO, "Licuadora", 64.33, 79.05, 74.15, 2.47, eTipoArt.PequeElectro, 15223.10);
        cPedidos Pedido19 = new cPedidos(Cliente19, ePrioridad.EXPRESS, "Televisor 82", 83.86, 52.19, 101.83, 43.9, eTipoArt.Televisor, 90180.73);
        cPedidos Pedido20 = new cPedidos(Cliente20, ePrioridad.NORMAL, "Computadora Personal", 61.37, 38.28, 28.43, 2.5, eTipoArt.Electronico, 20908.25);
        cPedidos Pedido21 = new cPedidos(Cliente21, ePrioridad.DIFERIDO, "Termotanque", 65.93, 69.73, 11.51, 38, eTipoArt.Linea_Blanca, 37344.75); 
        cPedidos Pedido22 = new cPedidos(Cliente22, ePrioridad.EXPRESS, "Freezer", 74.34, 79.43, 171.8, 56, eTipoArt.Linea_Blanca, 20731.00);
        cPedidos Pedido23 = new cPedidos(Cliente23, ePrioridad.NORMAL, "Lavarropas", 80.91, 44.37, 150.41, 70, eTipoArt.Linea_Blanca, 17272.02);
        cPedidos Pedido24 = new cPedidos(Cliente24, ePrioridad.DIFERIDO, "Tostadora", 75.89, 43.83, 34.45, 0.9, eTipoArt.PequeElectro, 42472.45);
        cPedidos Pedido25 = new cPedidos(Cliente1, ePrioridad.NORMAL, "Televisor 82", 83.86, 52.19, 101.83, 43.9, eTipoArt.Televisor, 90180.73);//
        cPedidos Pedido26 = new cPedidos(Cliente2, ePrioridad.NORMAL, "Cafetera", 70.94, 41.15, 75.37, 2.3, eTipoArt.PequeElectro, 47197.11);
        cPedidos Pedido27 = new cPedidos(Cliente3, ePrioridad.DIFERIDO, "Televisor 55", 47.74, 84.9, 51.6, 14.6, eTipoArt.Televisor, 95857.33);
        cPedidos Pedido28 = new cPedidos(Cliente4, ePrioridad.DIFERIDO, "Cocina", 65.64, 37.41, 46.2, 30, eTipoArt.Linea_Blanca, 44511.22);
        cPedidos Pedido29= new cPedidos(Cliente5, ePrioridad.NORMAL, "Licuadora", 64.33, 79.05, 74.15, 2.47, eTipoArt.PequeElectro, 15223.10);
        cPedidos Pedido30 = new cPedidos(Cliente6, ePrioridad.DIFERIDO, "Heladera", 39.94, 92.79, 37.24, 45, eTipoArt.Linea_Blanca, 31568.23);
        cPedidos Pedido31 = new cPedidos(Cliente7, ePrioridad.NORMAL, "Secarropa", 84.1, 97.65, 57.06, 10.9, eTipoArt.Linea_Blanca, 54316.51);
        cPedidos Pedido32 = new cPedidos(Cliente8, ePrioridad.NORMAL, "Mouse", 10.73, 90.1, 93.02, 0.100, eTipoArt.Electronico, 23332.94);
        cPedidos Pedido33 = new cPedidos(Cliente9, ePrioridad.DIFERIDO, "Molinillo de Cafe", 99.03, 92.3, 88.22, 4.46, eTipoArt.PequeElectro, 27265.86);
        cPedidos Pedido34 = new cPedidos(Cliente10, ePrioridad.DIFERIDO, "Webcam", 39.19, 10.9, 88.89, 0.150, eTipoArt.Electronico, 15017.83);
        cPedidos Pedido35 = new cPedidos(Cliente11, ePrioridad.NORMAL, "Televisor 62", 76.16, 85.26, 103.98, 17.1, eTipoArt.Televisor, 50854.50);
        cPedidos Pedido36 = new cPedidos(Cliente12, ePrioridad.DIFERIDO, "Televisor  68", 64.93, 53.19, 27.64, 20.5, eTipoArt.Televisor, 39757.75);
        cPedidos Pedido37 = new cPedidos(Cliente13, ePrioridad.NORMAL, "Televisor 52", 33.73, 50.59, 134.41, 11.5, eTipoArt.Televisor, 56517.98);
        cPedidos Pedido38 = new cPedidos(Cliente14, ePrioridad.NORMAL, "Tostadora", 75.89, 43.83, 34.45, 0.9, eTipoArt.PequeElectro, 42472.45);
        cPedidos Pedido39 = new cPedidos(Cliente15, ePrioridad.DIFERIDO, "Computadora Personal", 61.37, 38.28, 28.43, 2.5, eTipoArt.Electronico, 20908.25);
        cPedidos Pedido40 = new cPedidos(Cliente16, ePrioridad.DIFERIDO, "Microondas", 36.23, 74.68, 13.12, 12.5, eTipoArt.Linea_Blanca, 58699.77);
        cPedidos Pedido41 = new cPedidos(Cliente17, ePrioridad.NORMAL, "Webcam", 39.19, 10.9, 88.89, 0.150, eTipoArt.Electronico, 15017.83);
        cPedidos Pedido42 = new cPedidos(Cliente18, ePrioridad.DIFERIDO, "Mouse", 10.73, 90.1, 93.02, 0.100, eTipoArt.Electronico, 23332.94);
        cPedidos Pedido43 = new cPedidos(Cliente19, ePrioridad.NORMAL, "Teclado", 92.31, 79.94, 52.1, 0.55, eTipoArt.Electronico, 34657.74);
        cPedidos Pedido44 = new cPedidos(Cliente20, ePrioridad.NORMAL, "Licuadora", 64.33, 79.05, 74.15, 2.47, eTipoArt.PequeElectro, 15223.10);
        cPedidos Pedido45 = new cPedidos(Cliente21, ePrioridad.DIFERIDO, "Televisor 52", 33.73, 50.59, 134.41, 11.5, eTipoArt.Televisor, 56517.98);
        cPedidos Pedido46 = new cPedidos(Cliente22, ePrioridad.DIFERIDO, "Termotanque", 65.93, 69.73, 11.51, 38, eTipoArt.Linea_Blanca, 37344.75);
        cPedidos Pedido47 = new cPedidos(Cliente23, ePrioridad.NORMAL, "Freezer", 74.34, 79.43, 171.8, 56, eTipoArt.Linea_Blanca, 20731.00);
        cPedidos Pedido48 = new cPedidos(Cliente24, ePrioridad.DIFERIDO, "Lavarropas", 80.91, 44.37, 150.41, 70, eTipoArt.Linea_Blanca, 42472.45);
        #endregion

#region Carga
        ListaPedidos.Add(Pedido1);
        ListaPedidos.Add(Pedido2);
        ListaPedidos.Add(Pedido3);
        ListaPedidos.Add(Pedido4);
        ListaPedidos.Add(Pedido5);
        ListaPedidos.Add(Pedido6);
        ListaPedidos.Add(Pedido7);
        ListaPedidos.Add(Pedido8);
        ListaPedidos.Add(Pedido9);
        ListaPedidos.Add(Pedido10);
        ListaPedidos.Add(Pedido11);
        ListaPedidos.Add(Pedido12);
        ListaPedidos.Add(Pedido13);
        ListaPedidos.Add(Pedido14);
        ListaPedidos.Add(Pedido15);
        ListaPedidos.Add(Pedido16);
        ListaPedidos.Add(Pedido17); 
        ListaPedidos.Add(Pedido18);
        ListaPedidos.Add(Pedido19);
        ListaPedidos.Add(Pedido20); 
        ListaPedidos.Add(Pedido21);
        ListaPedidos.Add(Pedido22);
        ListaPedidos.Add(Pedido23);
        ListaPedidos.Add(Pedido24);
        ListaPedidos.Add(Pedido25);
        ListaPedidos.Add(Pedido26); 
        ListaPedidos.Add(Pedido27);
        ListaPedidos.Add(Pedido28);
        ListaPedidos.Add(Pedido29);
        ListaPedidos.Add(Pedido30);
        ListaPedidos.Add(Pedido31);
        ListaPedidos.Add(Pedido32);
        ListaPedidos.Add(Pedido33);
        ListaPedidos.Add(Pedido34);
        ListaPedidos.Add(Pedido35); 
        ListaPedidos.Add(Pedido36);
        ListaPedidos.Add(Pedido37);
        ListaPedidos.Add(Pedido38);
        ListaPedidos.Add(Pedido39);
        ListaPedidos.Add(Pedido40);
        ListaPedidos.Add(Pedido41);
        ListaPedidos.Add(Pedido42);
        ListaPedidos.Add(Pedido43);
        ListaPedidos.Add(Pedido44);
        ListaPedidos.Add(Pedido45);
        ListaPedidos.Add(Pedido46);
        ListaPedidos.Add(Pedido47);
        ListaPedidos.Add(Pedido48);
#endregion
        return;
    }

    public void crearvehiculos()
    {
        cCamion Furgon = new cCamion();
        cFurgoneta Furgoneta = new cFurgoneta();
        cCamioneta Camioneta = new cCamioneta();
        ListaVehiculos.Add(Furgon);
        ListaVehiculos.Add(Furgoneta);
        ListaVehiculos.Add(Camioneta);
    }
}//end cCocimundo

