///////////////////////////////////////////////////////////
//  cCocimundo.cs
//  Implementation of the Class cCocimundo
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:14
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cCocimundo {

	public cVehiculos m_cVehiculos;
	public cPedidos m_cPedidos;

	public cCocimundo(){

	}

	~cCocimundo(){

	}

	public void AgregarPedido(){

	}

	public void CalcularCosto(){

	}

	public void CalcularDepreacion(){

	}

	public void EliminarPedido(){

	}

	public void FinalDelDia(){

	}

	public cPedido QuitarPedido(){

		return null;
	}

}//end cCocimundo