///////////////////////////////////////////////////////////
//  cFurgoneta.cs
//  Implementation of the Class cFurgoneta
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:26
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cFurgoneta : cVehiculos {

	public cFurgoneta(){

	}

	~cFurgoneta(){

	}

}//end cFurgoneta