///////////////////////////////////////////////////////////
//  cPedidos.cs
//  Implementation of the Class cPedidos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:37
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Intrinsics.X86;

public enum ePrioridad : int{EXPRESS = 1, DOSDIAS = 2, NORMAL = 3, DIFERIDO = 4};
public struct Dimensiones
{
    public double ancho;
    public double largo;
    public double alto;
}
public enum eTipoArt : int { Linea_Blanca, Electrdomestico, Televisor }

public class cPedidos {

	static private int NumPedido = 0;
	private ePrioridad Prioridad;
	public cCliente Cliente;
    private string nombre;
    private Dimensiones dimens;
    private float peso;
    private double volumen;
    public eTipoArt TipoArticulo;

    public cPedidos(cCliente Cliente_, ePrioridad Prioridad_, string nombre_, double ancho_, double largo_, double alto_, float peso_, eTipoArt TipoArticulo_)
    {
        nombre = nombre_;
        dimens.ancho = ancho_;
        dimens.largo = largo_;
        dimens.alto = alto_;
        peso = peso_;
        volumen = ancho_ * largo_ * alto_;
        TipoArticulo = TipoArticulo_;
        NumPedido++;
		Cliente = Cliente_;
		Prioridad = Prioridad_;
	}
    ~cPedidos(){

	}
	public string getPrioridad()
    {
		
        switch (Prioridad)
        {
			case EXPRESS:
				return "express";
			case DOSDIAS:
				return "48 horas";
			case NORMAL:
				return "normal";
			case DIFERIDO:
				return "diferido";
			default:
				return "express";
		}
    }
	public void ModificarPrioridad()
    {
		Prioridad--;
    }
}//end cPedidos