///////////////////////////////////////////////////////////
//  cPedidos.cs
//  Implementation of the Class cPedidos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:37
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum ePrioridad : int
{

	EXPRESS = 1,
	DOSDIAS = 2,
	NORMAL = 3,
	DIFERIDO = 4

}
public class cPedidos {

	private readonly string NumPedido;
	private ePrioridad Prioridad;
	public cCliente Cliente;
	public List<cArticulos> Articulos;

	public cPedidos(){

	}

	~cPedidos(){

	}
	string getPrioridad()
    {
        switch (Prioridad)
        {
			case EXPRESS:
				return "express";
			case DOSDIAS:
				return "48 horas";
			case NORMAL:
				return "normal";
			case DIFERIDO:
				return "diferido";
		}
    }
	void ModificarPrioridad()
    {
		Prioridad = Prioridad - 1;
    }
}//end cPedidos