///////////////////////////////////////////////////////////
//  cPedidos.cs
//  Implementation of the Class cPedidos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:37
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cPedidos {

	private readonly string NumPedido;
	private ePrioridad Prioridad;
	public cCliente *Cliente ;
	public cArticulos *Articulos;

	public cPedidos(){

	}

	~cPedidos(){

	}

}//end cPedidos