///////////////////////////////////////////////////////////
//  cUbicacion.cs
//  Implementation of the Class cUbicacion
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:22
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cUbicacion {

	private eBarrio Barrio;
	private float x;
	private float y;

	public cUbicacion(){

	}

	~cUbicacion(){

	}

	/// 
	/// <param name="ubicacion"></param>
	public float CalcularDistancia(cUbicacion ubicacion){

		return 0;
	}

}//end cUbicacion