///////////////////////////////////////////////////////////
//  cUbicacion.cs
//  Implementation of the Class cUbicacion
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:22
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cUbicacion {

	private eBarrio Com_Part;
	private double x;
	private double y;

	public cUbicacion(eBarrio Barrio){
		Com_Part = Barrio;
		switch(Barrio) //me fijo que barrio es y se le asignan una coordenada en X e Y 
		{
            case eBarrio.Comuna_1:
                x = 14.1; //km a comuna 1 (desde liniers especificamente)
                y = 1.1; //km a comuna 1 (desde liniers especificamente)
                break;
            case eBarrio.Comuna_2:
                x = 13.5;
                y = 5.3;
                break;
            case eBarrio.Comuna_3:
                x = 12.7;
                y = 2.5;
                break;
            case eBarrio.Comuna_4:
                x = 12.3;
                y = 1.3;
                break;
            case eBarrio.Comuna_5:
                x = 10.4;
                y = 0.65;
                break;
            case eBarrio.Comuna_6:
                x = 8.7;
                y = 1.5;
                break;
            case eBarrio.Comuna_7:
                x = 7.6;
                y = 0.7;
                break;
            case eBarrio.Comuna_8:
                x = 6.6;
                y = -5.3;
                break;
            case eBarrio.Comuna_9:
                x = 0;
                y = 0;
                break;
            case eBarrio.Comuna_10:
                x = 2.7;
                y = 2.9;
                break;
            case eBarrio.Comuna_11:
                x = 4.0;
                y = 5.7;
                break;
            case eBarrio.Comuna_12:
                x = 5.9;
                y = 9.6;
                break;
            case eBarrio.Comuna_13:
                x = 9.1;
                y = 10.4;
                break;
            case eBarrio.Comuna_14:
                x = 10.8;
                y = 7.2;
                break;
            case eBarrio.Comuna_15:
                x = 6.7;
                y = 5.8;
                break;
            case eBarrio.VicenteLopez:
                x = 7.8;
                y = 15.5;
                break;
            case eBarrio.SanIsidro:
                x = 8.2;
                y = 19.9;
                break;
            case eBarrio.SanMartin:
                x = 2.4;
                y = 10.2;
                break;
            case eBarrio.TresdeFebrero:
                x = -2.1;
                y = 4.1;
                break;
            case eBarrio.Moron:
                x = -9;
                y = -1.2;
                break;
            case eBarrio.LaMatanza:
                x = -3.9;
                y = -4.6;
                break;
            case eBarrio.LomasdeZAmora:
                x = 10.3;
                y = -13.1;
                break;
            case eBarrio.Lanus:
                x = 13.9;
                y = -6.3;
                break;
            case eBarrio.Avellaneda:
                x = 15.6;
                y = -4.6;
                break;
            default:
                x = 0;
                y = 0;
                break;
        }
	}

	~cUbicacion(){

	}
    public double getX() { return x; }
    public double getY() { return y; }

    public eBarrio GetBarrio() { return Com_Part; }

    public string to_String() //el tostring de las ubicaciones
    {
        string texto;
        switch (Com_Part)
        {
            case eBarrio.Comuna_1:
                texto = "Comuna 1";
                break;
            case eBarrio.Comuna_2:
                texto = "Comuna 2";
                break;
            case eBarrio.Comuna_3:
                texto = "Comuna 3";
                break;
            case eBarrio.Comuna_4:
                texto = "Comuna 4";
                break;
            case eBarrio.Comuna_5:
                texto = "Comuna 5";
                break;
            case eBarrio.Comuna_6:
                texto = "Comuna 6";
                break;
            case eBarrio.Comuna_7:
                texto = "Comuna 7";
                break;
            case eBarrio.Comuna_8:
                texto = "Comuna 8";
                break;
            case eBarrio.Comuna_9:
                texto = "Comuna 9";
                break;
            case eBarrio.Comuna_10:
                texto = "Comuna 10";
                break;
            case eBarrio.Comuna_11:
                texto = "Comuna 11";
                break;
            case eBarrio.Comuna_12:
                texto = "Comuna 12";
                break;
            case eBarrio.Comuna_13:
                texto = "Comuna 13";
                break;
            case eBarrio.Comuna_14:
                texto = "Comuna 14";
                break;
            case eBarrio.Comuna_15:
                texto = "Comuna 15";
                break;
            case eBarrio.VicenteLopez:
                texto = "Vicente Lopez";
                break;
            case eBarrio.SanIsidro:
                texto = "San Isidro";
                break;
            case eBarrio.SanMartin:
                texto = "San Martin";
                break;
            case eBarrio.TresdeFebrero:
                texto = "Tres de Febrero";
                break;
            case eBarrio.Moron:
                texto = "Moron";
                break;
            case eBarrio.LaMatanza:
                texto = "La Matanza";
                break;
            case eBarrio.LomasdeZAmora:
                texto = "Lomas de Zamora";
                break;
            case eBarrio.Lanus:
                texto = "Lanus";
                break;
            case eBarrio.Avellaneda:
                texto = "Avellaneda";
                break;
            default:
                texto = "Default";
                break;
        }
        return texto;
    }
}//end cUbicacion
