///////////////////////////////////////////////////////////
//  cVehiculos.cs
//  Implementation of the Class cVehiculos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:17
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public class cVehiculos {

    protected int Cant_Viajes;
    protected double Capacidad_Max_Combustible;
    protected float Carga_Util;
    protected double Consumo;
    protected Dimensiones dimens_vehiculo;
    protected float Peso_Max;
    protected int Viajes_Realizados;
	protected double Vol_Max;
    protected double distanciarecorrida;
    protected double preciocomb;

	public cVehiculos(){

	}

	~cVehiculos(){

	}
    public double getconsumo() { return Consumo; }
    public double getCapMaxComb() { return Capacidad_Max_Combustible; }
    public double getdistanciarecorrida() { return distanciarecorrida; }
    public void setdistanciarecorrida(double distancia) { distanciarecorrida = distancia; }

    public double getpreciocomb() { return preciocomb; }
    /// 
    /// <param name="pedido"></param>
    public void CargarVehiculo(cPedidos pedido){


	}
    public int getVol_Max()
    {
        return Convert.ToInt16(Vol_Max);
    }


}//end cVehiculos