///////////////////////////////////////////////////////////
//  cVehiculos.cs
//  Implementation of the Class cVehiculos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:17
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class cVehiculos {

	private readonly int Cant_Viajes;
	private readonly float Capacidad_Max_Combustible;
	private readonly float Carga_Util;
	private readonly int Consumo;
	private struct Dimensiones;
	private readonly float Peso_Max;
	private int Viajes_Realizados;
	private readonly float Vol_Max;

	public cVehiculos(){

	}

	~cVehiculos(){

	}

	/// 
	/// <param name="pedido"></param>
	public void CargarVehiculo(cPedido pedido){

	}

}//end cVehiculos