///////////////////////////////////////////////////////////
//  eBarrio.cs
//  Implementation of the Enumeration eBarrio
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:31
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



/// <summary>
/// Todos los barrios de CABA y primer cordón del Conurbano
/// </summary>
public enum eBarrio : int {

	Barrios CABA,
	Barrios 1er Cordon

}//end eBarrio