///////////////////////////////////////////////////////////
//  Electrodomesticos.cs
//  Implementation of the Class Electrodomesticos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:46
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Electrodomesticos : cArticulos {

	public Electrodomesticos(){

	}

	~Electrodomesticos(){

	}

}//end Electrodomesticos