///////////////////////////////////////////////////////////
//  ePrioridad.cs
//  Implementation of the Enumeration ePrioridad
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:35
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum ePrioridad : int {

	EXPRESS = 1, 
	DOSDIAS = 2,
	NORMAL = 3,
	DIFERIDO = 4

}//end ePrioridad