///////////////////////////////////////////////////////////
//  Linea_Blanca.cs
//  Implementation of the Class Linea_Blanca
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:39
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Linea_Blanca : cArticulos {

	public Linea_Blanca(){

	}

	~Linea_Blanca(){

	}

}//end Linea_Blanca