///////////////////////////////////////////////////////////
//  Pequenios_Electrodomesticos.cs
//  Implementation of the Class Pequenios_Electrodomesticos
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:42
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Pequenios_Electrodomesticos : cArticulos {

	public Pequenios_Electrodomesticos(){

	}

	~Pequenios_Electrodomesticos(){

	}

}//end Pequenios_Electrodomesticos