///////////////////////////////////////////////////////////
//  Televisores.cs
//  Implementation of the Class Televisores
//  Generated by Enterprise Architect
//  Created on:      09-nov.-2022 15:59:44
//  Original author: HP
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Televisores : cArticulos {

	public Televisores(){

	}

	~Televisores(){

	}

}//end Televisores